services:
- docker
install: make build
stages:
- name: echo
- name: publish
  if: branch = main AND type != pull_request
jobs:
  include:
  - stage: echo
    script: echo
  - stage: publish
    name: Publish production image
    script:
    - make publish
env:
  global:
  - secure: ONk4ddJfFbjnzDfKKHbADPIsI+7rqgY3uHLGvk8WkEi9MlhlrxAjGKAhUfIPP4Z3RCjYJdBsTICjGrFICXG1WgMN2lXalQ130XYMjoBHW7Q5KFb/pkoj6vWN8ZsTvVIqcSjPfEzk0uPtR74fL3oytCrgl4+TFKHbdDI8cNIYjidOc5vG5sXpW+z6Ct1iPHTvRQlvsLAZQoAw89s8O3kJ++ZSa59L2F7LfpmgOpPAl5p2HuE0ZZqncyHMmeqvftIQlqwRDq7yk3YX5CbrEEkRKoT7P5B0JQVYJDbIme0J7LA61Pg4PkmTYc7fPtTsXKATuACqH4NwkhCGm+T49zDEavjDhdCkVw9MduWbiTSAqBy/V64Y+9EaQiJ+xfXKVjW62DU+w43bk4pG3/vRcNAc35jrW5YQo6dPqDObTSaFWw9dK/ODhGvfOeZaRqj+QyDY8arq2ekiDBE88uu8xCCAGTWX24Dchl7Eb4aIfw5Rwr/O6hHd1io0Li35CWlJqk7CZstdQmXYeWTiX0hD6eG+KvWnirpt4xIQJuHM8cNHrOGss+zKmgCvsp2AZ++SJ3NnWIU20uuzAHUGM72bsONqd6wvIjq1rEYrO7kUnfvQA/9NVIY1JkgQEiNqXDe1oM0DMlWG6bNJwHupBWf897alho0fSWZzs5SllSEbF+f6o+M=
  - secure: vbDmO30th3khFUSbdaCTdTBIc7UoEmIdrgWIuzeX6F/iw28lFY7I/5giMLvgXtfpXJBGmIMfy6VyBcfhEZOR12fLU2e0HmF+rBohAjJDG/3WtXZ6OFVwWuLX97DyZXiCQz5fB/w8HnSvNlFvWDGUxzjvs1Ab0WKb2s0JKPn/bHT6bNfJ+N9LR3QAGFoVFD+hEOzIUQzSe9LIYAOBRyGzrYolA1wN71djjSLgwI40avJo/pOgr5oVqO0jm2ObAOtm7io5bBLacOzl8zPyEgZfUogbvaQ5izqD2wvwwadjme6SBDXOMdJTyr8vcTR9PnW7+IDLR2F7GhLZXi4jq2CYLWW7/xxIsqqYsGteB2kJ0Qb5nVvvIVF1JSBRUQTZK+7m/fVgS6TTCuC1hpEvSbtBrMxpEB/Us40d0nUG2Fs7/DzSb7Z4M+E++6rt5ccX2liAPQhfT8siAhkksiBOnmdrWE56u8Z+93yD+aYIV8fDoba2Wr3fTZDdzLoaLkXLimfPVJpyrR0ccZ8PNWH4zX12qVZJ6XK+I+N/bKi7g4ZthkcGtGu+fjBq1BcdgBF/dkd+ePlik224NfTx42dm18gbnNXEcoULU8o9XZ9DnAKxsAkg+6t8uC71gu3cUSSMJgkfjopMQpyjqoXyU8XV0OM2bTjqsP9XI/laZl0tZpeqJOI=
