ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=3.0.6
FROM ${REPOSITORY}/ncigdc/amzn2023-builder:${BUILDER_TAG} AS builder

ARG VERSION

ENV URL=http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${VERSION}.zip

RUN dnf install -y java-11-amazon-corretto
# Example download and compile step
RUN cd /opt && wget $URL \
	&& unzip fastqc_v${VERSION}.zip \
	&& rm -rf fastqc_v${VERSION}.zip \
	&& ls \
	&& cd FastQC \
	&& chmod +x fastqc \
	&& ln -s /opt/FastQC/fastqc /usr/local/bin/fastqc \
	&& sed -i 's/kmer[[:space:]]\+ignore[[:space:]]\+1/kmer ignore 0/' Configuration/limits.txt \
	&& sed -i 's/assistive_technologies/#assistive_technologies/' /etc/java-11-openjdk/accessibility.properties
# For a multi-stage build
FROM ${REPOSITORY}/ncigdc/amzn2023:${BUILDER_TAG}

COPY --from=builder /usr/local/* /usr/local/
